baseurl : /homepage
BASE_PATH : http://wuhu-ife.github.io/homepage


pygments: true
paginate: 10


archive_path: /homepage/blogs.html
categories_path : /homepage/blogs.html
tags_path : /homepages/blogs.html

title : Welcome to My Homepage!
author : 
  name : Hu Wu
  email : wuhu728@gmail.com
  github : https://github.com/wuhu-ife
